print("Welcome to the love calculator")
n1 = input("Enter your name : ")
n2 = input("Enter crush name : ")
c1 = n1.count("t")
c2 = n1.count("r")
c3 = n1.count("u")
c4 = n1.count("e")
c5 = n1.count("l")
c6 = n1.count("o")
c7 = n1.count("v")
c8 = n1.count("e")
You = c1+c2+c3+c4+c5+c6+c7+c8
d1 = n2.count("t")
d2 = n2.count("r")
d3 = n2.count("u")
d4 = n2.count("e")
d5 = n2.count("l")
d6 = n2.count("o")
d7 = n2.count("v")
d8 = n2.count("e")
crush = d1+d2+d3+d4+d5+d6+d7+d8
print(f"Love between Both of you is \n{You}{crush}%")